- name: Configure the developer environment (Node.js and .NET)
  hosts: app_servers
  become: yes
  tasks:
    - name: Step 1 - Download the Microsoft repository configuration 
      get_url:
        url: https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
        
    - name: Step 2 - Install the configuration file on the system
      apt:
        deb: /tmp/packages-microsoft-prod.deb
        state: present
      ignore_errors: yes

    - name: Step 4 - Download .NET
      get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: /tmp/dotnet-install.sh
        mode: '0755'
        
    - name: Step 5 - Run script and instalation .NET 10
      command: /tmp/dotnet-install.sh --channel 10.0 --install-dir /usr/share/dotnet
      args:
        creates: /usr/share/dotnet/dotnet

- name: Configure the application environment
  hosts: app_servers
  become: yes
  tasks:
    - name: Install required runtime environments
      apt:
        name:
          - apt-transport-https
          - nodejs
          - npm
          - redis-server
          - rabbitmq-server
        state: present
        update_cache: yes
