# Database access
- name: Configure secure access to the database
  hosts: db_servers
  become: yes
  vars_files:
    - secrets.yml # Load our encrypted file

  tasks:
    - name: Step 0 - Install the ACL package (required for user switching)
      apt:
        name: acl
        state: present

    - name: Step 1 - Install the Python driver for PostgreSQL
      apt:
        name: python3-psycopg2
        state: present

    - name: Step 2 - Create the database user
      community.postgresql.postgresql_user:
        name: "{{ vault_db_user }}"
        password: "{{ vault_db_password }}"
        role_attr_flags: "NOSUPERUSER,CREATEDB"
      become_user: postgres
      
    - name: Step 3 - Create the database 
      community.postgresql.postgresql_db:
        name: "{{ vault_db_name }}"
        owner: "{{ vault_db_user }}"
      become_user: postgres

# Application services
- name: Configure secure access to app services
  hosts: app_servers
  become: yes
  vars_files:
    - secrets.yml # Load our encrypted file

  tasks:
    # --- REDIS ---
    - name: REDIS | Set password from vault
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^# requirepass|^requirepass '
        line: "requirepass {{ vault_redis_password }}"
      notify: Restart Redis

    # --- RABBITMQ ---
    - name: RABBITMQ | Add administrator from Vault
      community.rabbitmq.rabbitmq_user:
        user: "{{ vault_rabbit_user }}"
        password: "{{ vault_rabbit_password }}"
        tags: administrator
        permissions:
          - vhost: /
            configure_priv: .*
            write_priv: .*
            read_priv: .*
        state: present
        
  handlers:
    - name: Restart Redis
      service: 
        name: redis-server
        state: restarted